# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45db7f6c49e31ca3c8620aac181d485a46ce1d9de0ea912e02823b03a238509740cbb197f04f26a682791c60d8599e73441032af17f6605d093c645daf2b66f8

test:
  secret_key_base: 2538ec82c38700520d415c5807b88747220f5ae50384dfe0c2bbeca3beb579360254f6a0142ea6de68e46ae377d3a306de293b393f8e95af3d41bc7bfcea91bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
